### ISSUE TITLE
id3 tag cannot be read properly

### ISSUE THREAD

**Issue by bjoernbusch** [thawn/ttmp32gme#27]
I have downloaded ttmp32gme for both Windows and Mac in the latest version and I'm having issues with the id3 tag of two mp3 files. I can properly add them to the library and I see cover image and and so on, but when I start the conversion process, I get the following errors in the log window:

```
[MSG] using tttool: /var/folders/c2/g3prhp6s70g8482ys89x6xvr0000gn/T/par-626a6f65726e/cache-4509fd5a9d6526bfb25b880d00886142abdae5c6/inc/lib/tttool
[ERROR] No useable id3 info found in /Users/bjoern/Library/Application Support/ttmp32gme/library/temp/1/FILENAME.mp3.
Please add an id3v2 tag to your mp3 file in order to get proper album and track info.
Use of uninitialized value in exists at TTMp32Gme/LibraryHandler.pm line 299.
copying albums to library
deleting /Users/bjoern/Library/Application Support/ttmp32gme/library/temp
/var/folders/c2/g3prhp6s70g8482ys89x6xvr0000gn/T/par-626a6f65726e/cache-4509fd5a9d6526bfb25b880d00886142abdae5c6/inc/lib/tttool --dpi 1200 --pixel-size 2 assemble FILENAME.yaml
dyld: Library not loaded: @executable_path/libgmp.10.dylib
  Referenced from: /var/folders/c2/g3prhp6s70g8482ys89x6xvr0000gn/T/par-626a6f65726e/cache-4509fd5a9d6526bfb25b880d00886142abdae5c6/inc/lib/tttool
  Reason: image not found
[ERROR] 
Use of uninitialized value in exists at TTMp32Gme/LibraryHandler.pm line 318.
```

Is there any hint on how I can debug this? In iTunes, I see perfect information. I couldn't find another free id3 tag app for Mac quickly. Any help would be appreciated.

**Comment by thawn** [comment]
@bjoernbusch thank you very much for your bug report. I have a few questions that may help me track down the problem.
There seem to be several issues here:

1) ttmp32gme complains about the id3 tags: Do your mp3s have both titles track numbers in the id3? I suspect that this error message is caused by missing track numbers. However, this error is not critical and the program can work around it. On my mac I am using [kid3](https://kid3.sourceforge.io/#download) to edit id3 tags. The most important tags for ttmp32gme are `album`, `title` and `track`.

2) The main problem seems to be that tttool is missing a library. (libgmp.10.dylib) I think I just fixed that issue in the latest release a couple of minutes ago. Could you please test version 0.3.0 if that works for you?

**Comment by bjoernbusch** [comment]
Awesome! Yes, the track number was missing, since it's an audiobook with one track. With the latest release, I did not have to make such changes and it just worked! Thanks, works like a charm, even with the printed OID, no issues!

**Comment by thawn** [comment]
good to hear that the latest release works for you. Thanks for letting me know!
