### ISSUE TITLE
Export images

### ISSUE THREAD

**Issue by Suplanus** [thawn/ttmp32gme#38]
First of all thanks for this great repo 🦄

I would love to see a button "Export images" which exports all the OID-Code image files to a folder. Filename should be the track name.

So I can easily use it in my own game 🎲

Workaround:
I drag them from the browser to my game-image.

**Comment by thawn** [comment]
@Suplanus thank you very much for your feature request. I am glad that ttmp32gme got you hooked on experimenting with your own TipToi projects ;-)

You can find the oid-code images as png files on your hard disk under `%appdata%\ttmp32gme\oid-cache`. The files  are named `<OID number>-<size in mm>-<resolution>.png`.

On Windows: Open Explorer and type `%appdata%`

On mac: in a terminal type `open $home/Library/Application\ Support/ttmp32gme`

ttmp32gme re-uses the control OIDs (oid code >1000) for play/pause/track etc. The only codes that are unique to the albums are the power-on codes (in the range below 1000)

You can also very easily create oid code images [with tttool on the command line](https://tttool.readthedocs.io/de/latest/tttool-referenz.html#oid-codes-erzeugen). This is the command line program that also ttmp32gme uses in the background.

For your own projects, I highly recommend using [tttool](https://tttool.readthedocs.io/de/latest/) directly. It is much more flexible than ttmp32gme.

By designing your own printable sheets, you are already doing the most difficult part of the job that ttmp32gme is trying to do for you. The very latest point where you should switch to tttool is when you realize that you would like to implement a little bit more complex routines (like question and answer games etc). At that point you will need to start writing your own yml files and compile them with tttool. At that point, you are doing everything on the command line that ttmp32gme is providing a user interface for.

ttmp32gme is not and will never be a full user interface to tttool. This would simply be much more work than I can afford in my free time. I hope that you understand that I will not add the requested feature, because it would inevitably invite more feature requests asking for layout editors, yaml code editors and the like. That being said, anyone is very welcome to fork the code and use it as a basis for a tttool user interface :-).

**Comment by Suplanus** [comment]
Thank you very much for this great answer.
I will look into it!
💕
