### ISSUE TITLE
Scaling issue when printing

### ISSUE THREAD

**Issue by severin-lemaignan** [thawn/ttmp32gme#4]
Hello! Great project, thank you for sharing it!

I'm trying to get it to run on Linux, and everything seems ok, except for the generated PDF: the scale looks quite wrong. I've tried both with firefox and chrome, but I suspect the issue rather lies with `wktmltopdf`.

I attach on of the generated PDF (as you can see, the page is even cropped).

Any idea?
[print.pdf](https://github.com/thawn/ttmp32gme/files/768460/print.pdf)

**Comment by thawn** [comment]
Which version of wkthmltopdf do you use?

On windows, I use wkhtmltopdf 0.13.0 alpha (because that comes with a 
more modern webkit engine that fixed some issues).

PDF generation is mainly intended for windows where printing from the 
browser does not work well due to a crappy printing backend.

I have had reports from other users that printing directly from firefox 
under linux works as expected, meaning that you don't actually need to 
generate a pdf (it may also work to generate a pdf by printing to pdf 
from firefox).

Cheers

Till

**Comment by severin-lemaignan** [comment]
```
$ wkhtmltopdf --version
wkhtmltopdf 0.12.2.4
```
But indeed, printing directly from Firefox worked out well (on a HP ENVY 5540).
Maybe we should add a button 'Print' next to the 'Save to PDF', as it was not obvious that the page was intended to be printed out.
