### ISSUE TITLE
Error when making GME

### ISSUE THREAD

**Issue by alexanderschaab** [thawn/ttmp32gme#40]
Hi,

this is when I try to make a GME:
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at Music/Tag.pm line 1066, <DATA> line 1.
Updating config...
Update successful.
[MSG] Server running on port: 10020
Open http://127.0.0.1:10020/ in your favorite web browser to continue.

[MSG] using tttool: C:\Users\maria\AppData\Local\Temp\par-6d61726961\cache-d4cd2848b70ff6e5ca5e050927fb42b31959a03d\inc\lib\tttool.exe
C:\Users\maria\AppData\Local\Temp\par-6d61726961\cache-d4cd2848b70ff6e5ca5e050927fb42b31959a03d\inc\lib\tttool.exe --dpi 1200 --pixel-size 2 assemble Biene_Maja_1_-_Maja_lernt_fliegen.yaml
[ERROR] AesonException "Error in $.scripts.play: expected [a], encountered Null"

Not sure what I am doing wrong.

Thanks for helping.

Best
Alex

**Comment by thawn** [comment]
Could be a problem with file names. Try to rename the mp3 files without any special characters (umlaut, exclamation point etc.). Also, make sure that the mp3 files have proper id3 tags.

**Comment by alexanderschaab** [comment]
What do you mean with proper Id3 tags?

**Comment by thawn** [comment]
Use an id3 tag editor [like this one](https://www.mp3tag.de/en/) to set the album, artist and title tags of the mp3 files.

**Comment by thawn** [comment]
@alexanderschaab were you able to resolve the issue?

**Comment by alexanderschaab** [comment]
no

Am Mi., 2. Dez. 2020 um 08:17 Uhr schrieb thawn <notifications@github.com>:

**Comment by thawn** [comment]
could you please send me an example file?

**Comment by thawn** [comment]
@alexanderschaab In order to help you, I need to be able to reproduce the issue. 

Could you please:
* send me the .yaml files from the library `C:\Users\[username]\AppData\Roaming\ttmp32gme\Library`?
* post a screenshot of what the file structure inside one of the subfolders of Library looks like?
* Send me an example mp3 file

Since I have not heard back from you in a while, I am closing the issue for now.
If you still have problems, please answer my questions above and re-open the issue.
