### ISSUE TITLE
converting to .ogg broken

### ISSUE THREAD

**Issue by derpicknicker1** [thawn/ttmp32gme#42]
There are two issues with the conversion to `.ogg` files:
1.  On windows the file-name-arguments in the conversion command have to be in double quotation marks instead of single quotation marks https://github.com/thawn/ttmp32gme/blob/8a3c369312dc4637b1519cf32f6c0df49a4c89e1/src/TTMp32Gme/TttoolHandler.pm#L104
should be ==> `` `$ff_command -i "$source_file" -ar 22050 -ac 1 "$target_file"`; ``
But honestly I don't know if this breaks behaviour on linux/mac.

2.  If there is a cover art integrated in the `.mp3` file, ffmpeg tries to convert not only audio stream but also a video stream. This "breaks" the resulting `.ogg` file in a way, that the tiptoi can not play the `.gme`
**Solution:** use `-map a` as parameter for ffmpeg to tell it to extract only audio data.

But apart of these solvable problems it is a great tool which will make my niece very happy 😀

**Comment by thawn** [comment]
Thank you very much for the bug report!

Could you please provide the error messages that you get when you try ogg conversion?

In my tests on windows, ogg conversion worked. Admittedly, the last time I tested that feature on windows was a while ago (my development machine is a mac).

What I know for sure is that double quotes will create problems on linux and mac: In double quotes, special command line characters will not be escaped, which would enable privilege escalation in case the software is run on a remote machine.

It would be great if you could help me figure out exactly what causes the problems in your case, so that I can fix them some other way (probably by just renaming files to remove any special characters).

**Comment by derpicknicker1** [comment]
> Could you please provide the error messages that you get when you try ogg conversion?

Was the same problem like in this issue: https://github.com/thawn/ttmp32gme/issues/35

**Comment by thawn** [comment]
In that case, I will close this one as a duplicate of #35. please continue the discussion there.
