### ISSUE TITLE
lost Library

### ISSUE THREAD

**Issue by edvagi** [thawn/ttmp32gme#43]
on the first steps with ttmp32gme (my child's are playing already audio books from a self printed sheet) on one day the library seems to bee empty. I tried to reconnect the usb tiptoi, sopped, started ttmp32gme on my ubuntu with /media/.../... parameter, also without. In some way i was able to restore the library. But i restarted the laptop again an the library seems to be gone.
Also i tried to restart (stop and start again) the ttmp32gme with and without plugged tiptio.

Have you some hints for me? Or is it a issue??
Thanx!
TG

**Comment by thawn** [comment]
thank you for your bug report. This sounds very weird. I have never encountered anything like it. 
Unfortunately, without additional information, I have no way of reproducing and/or analyzing the issue.

Did you change the location of the library in the ttmp32gme configuration?
Did you notice any error messages in the command line window that opens when you start ttmp32gme?

When the library is gone in ttmp32gme is it also gone on disk? By default, the Library is stored in a hidden folder `C:\Users\[username]\AppData\Roaming\ttmp32gme`

Inside that folder, there is also a `config.sqlite` file. I suspect that in your case, this file gets corrupted somehow.

**Comment by thawn** [comment]
@edvagi  I just read that you are using ubuntu (sorry that I missed that before).

On linux, please NEVER change the path to the library in the configuration (this will definitely break the docker images and cause data loss if you use docker)!!!

The library is stored under `~/.ttmp32gme/`.

Can you please detail a bit more about how you start and stop ttmp32gme? Are you using the docker images?

Since I have not heard from you in a while, I am closing the issue for now. If you still need help, just answer my questions above and re-open.
